#Create Search Terms Vector - Modify as desired. Main script will take a sample of 30 of these terms to search.

searchTerms <- c(
	"Angora",
"Astrologer",
"Greece",
"Librarian",
"Portfolio",
"Saddle",
"Shakedown",
"Shed",
"Thigh",
"Torchiere",
"Bat",
"Energy",
"Hurry",
"Macadamia",
"Massage",
"Peacoat",
"People",
"Pull",
"Reef",
"Swiss",
"Care",
"Cornet",
"Emergence",
"Grandfather",
"One",
"Ounce",
"Room",
"Shovel",
"Stair",
"Turkey",
"Kansas City, Missouri",
"Minneapolis, Minnesota",
"Jersey City, New Jersey",
"Laredo, Texas",
"Chicago, Illinois",
"Rochester, New York",
"Atlanta, Georgia",
"Modesto, California",
"Detroit, Michigan",
"Tucson, Arizona",
"Corpus Christi, Texas",
"Baltimore, Maryland",
"Birmingham, Alabama",
"Columbus, Ohio",
"St. Paul, Minnesota",
"Arlington, Virginia",
"Seattle, Washington",
"Tampa, Florida",
"Plano, Texas",
"Olive Garden",
"Applebee's",
"Boston Market",
"Joe's Crab Shack",
"Black-eyed Pea",
"Rainforest Cafe",
"Hooters",
"Perkins Restaurant and Bakery",
"Chipotle Mexican Grill",
"Golden Corral",
"Bob Evans Restaurants",
"Hoss's Steak and Sea House",
"Boston Pizza",
"Friendly's",
"Charlie Brown's Steakhouse",
"Famous Dave's",
"Quaker Steak & Lube",
"Tony Roma's",
"Steak 'n Shake",
"Qdoba Mexican Grill",
"Bubba Gump Shrimp Company",
"Café Rouge",
"T.G.I. Friday's",
"On the Border Mexican Grill & Cantina",
"Bahama Breeze",
"Carrabba's Italian Grill",
"Benihana",
"Black Angus Steakhouse",
"Tony Roma's",
"Bennigan's",
"Jurassic World",
"Ted 2",
"Iron Man",
"The Great Gatsby (2013)",
"The Hunger Games",
"Titanic",
"Ratatouille",
"Burnt",
"The Incredibles",
"Toy Story 2",
"The Princess and the Frog",
"Snow White & the Huntsman (Extended Edition)",
"Avatar (2009)",
"Thor: The Dark World",
"The Cove",
"Cars",
"Harry Potter and the Order of the Phoenix",
"Spectre",
"The Notebook",
"Hotel Transylvania 2",
"Goosebumps",
"Star Wars: A New Hope",
"The Dark Knight",
"The Jungle Book",
"The Island",
"The Proposal",
"Inside Out (2015)",
"The Hunger Games: Mockingjay - Part 2",
"The Man from U.N.C.L.E.",
"The Other Woman",
"Sicario",
"Norm of the North",
"Crimson Peak",
"Snow White and the Seven Dwarfs (1937)",
"Star Wars: Return of the Jedi",
"Interstellar",
"Man of Steel (2013)",
"Minions",
"Snow White & the Huntsman",
"Pitch Perfect",
"The Adderall Diaries",
"Love the Coopers",
"Project Nim",
"Aladdin",
"Graffiti Bridge",
"The Lord of the Rings: The Two Towers",
"Point Break (2015)",
"Joy",
"The Wolf of Wall Street",
"The Lady In the Van",
"Ant-Man",
"Southpaw",
"Tangled",
"10 Things I Hate About You",
"Ride Along 2",
"American Sniper",
"Crazy, Stupid, Love",
"The Intern",
"Purple Rain",
"Brooklyn",
"IMAX: Born to Be Wild",
"Unity",
"The Martian",
"Requiem for the American Dream",
"Toy Story",
"Holidays",
"Up",
"Unbranded",
"Clue",
"Star Wars: The Empire Strikes Back",
"Harry Potter and the Deathly Hallows, Part 1",
"Ip Man 3",
"Scouts Guide to the Zombie Apocalypse",
"The Wizard of Oz",
"The Forest",
"Raising Arizona",
"Iron Man 2",
"The Age of Adaline",
"Guardians of the Galaxy",
"Finding Nemo",
"Sisters",
"Spy",
"Krampus",
"The Danish Girl",
"Justice League vs. Teen Titans",
"The Sound of Music",
"The Good Dinosaur",
"Tumbledown",
"Room",
"Natural Born Pranksters",
"Frozen",
"The Hateful Eight",
"Star Wars: Revenge of the Sith",
"Monsters University",
"Megamind",
"Kung Fu Panda",
"Legend (2015)",
"Fastball",
"Fifty Shades of Black",
"Harry Potter and the Chamber of Secrets (Extended Version)",
"The Other Guys",
"Man Up",
"Iron Man 3",
"Daddy's Home",
"The Avengers",
"Just Eat It: A Food Waste Story",
"The Night Before",
"The Big Short",
"Harry Potter and the Half-Blood Prince",
"The Hunger Games: Mockingjay - Part 1",
"The Last Lions",
"Harry Potter and the Sorcerer's Stone",
"Kung Fu Panda 2",
"The Dark Knight Rises",
"Alvin and the Chipmunks: The Road Chip",
"Cars 2",
"Ex Machina",
"Flight 7500",
"In the Heart of the Sea",
"Star Wars: The Force Awakens",
"Willy Wonka & the Chocolate Factory",
"Hostile Border",
"Daniel Tosh: People Pleaser",
"Anomalisa",
"Zero Dark Thirty",
"The Choice",
"Big Hero 6",
"Drunk, Stoned, Brilliant, Dead: The Story of the National Lampoon",
"Alice In Wonderland",
"The Longest Week",
"American Ultra",
"Colonia",
"The Peanuts Movie",
"Heat (1995)",
"Harry Potter and the Prisoner of Azkaban",
"Chasing Ice",
"Alice In Wonderland (1951)",
"GMO OMG",
"A Royal Night Out",
"The Gift (2015)",
"Creed",
"Black Swan",
"The Revenant",
"Maze Runner: The Scorch Trials",
"Live Die Repeat: Edge of Tomorrow",
"High School Musical 3: Senior Year",
"Carol",
"Inception",
"Bridge of Spies",
"Toy Story 3",
"The Sandlot",
"Everest (2015)",
"Brave",
"Big Men",
"Captain America: The Winter Soldier",
"Green Lantern Extended Cut (2011)",
"The Invitation",
"Fifty Shades of Grey",
"Avengers: Age of Ultron",
"The 5th Wave",
"Spotlight",
"Concussion",
"The Hunger Games: Catching Fire",
"Jane Got a Gun",
"Pitch Perfect 2",
"Wreck-It Ralph",
"Straight Outta Compton (Unrated Director's Cut)",
"Mr. Right (2016)",
"Dr. Seuss' the Lorax",
"Temps",
"Grizzly Man",
"Secret In Their Eyes (2015)",
"The Visit",
"Harry Potter and the Deathly Hallows, Part 2",
"Despicable Me 2",
"Steve Jobs (2015)",
"The LEGO Movie",
"Harry Potter and the Goblet of Fire",
"The Little Mermaid",
"Trainwreck",
"Under the Cherry Moon",
"Lego Scooby Doo: Haunted Hollywood",
"The Last Song",
"Pan",
"Indiana Jones and the Raiders of the Lost Ark",
"Nina",
"March of the Penguins",
"Ride Along",
"Captain America: The First Avenger",
"Black Mass",
"Mary Poppins",
"Monsters, Inc.",
"Amy",
"Divergent",
"Prescription Thugs",
"IMAX: To the Arctic",
"Sleeping With Other People",
"We're the Millers (2013)",
"Affine transformation",
"Affirming the antecedent",
"Affirming the consequent",
"Alternative Hypothesis",
"Ante",
"Antecedent",
"Appeal to Ignorance",
"Applet",
"Association",
"Average",
"Axioms of Probability",
"Base rate fallacy",
"Bayes' Rule",
"Bernoulli's Inequality",
"Bias",
"Bimodal",
"Binomial Coefficient",
"Binomial Distribution",
"Binomial Theorem",
"Bivariate",
"Blind, Blind Experiment",
"Bootstrap estimate of Standard Error",
"Box model",
"Breakdown Point",
"Categorical Variable",
"Causation, causal relation",
"Central Limit Theorem",
"Certain Event",
"Chance variation, chance error",
"Chebychev's Inequality",
"Chi-square curve",
"Chi-square Statistic",
"Class Boundary",
"Class Interval",
"Cluster Sample",
"Combinations",
"Complement",
"Complement rule",
"Compound proposition",
"Conditional Probability",
"Confidence Interval",
"Confidence Level",
"Confounding",
"Continuity Correction",
"Consequent",
"Continuous Variable",
"Contrapositive",
"Control",
"Controlled experiment",
"Controlled, randomized experiment",
"Control for a variable",
"Control group",
"Convenience Sample",
"Converge, convergence",
"Convergence in probability",
"Converse",
"Correlation",
"Correlation coefficient",
"Counting",
"Countable Set",
"Cover",
"Coverage probability",
"Critical value",
"Cross-sectional study",
"Cumulative Probability Distribution Function (cdf)",
"de Morgan's Laws",
"Deck of Cards",
"Dependent Events, Dependent Random Variables",
"Dependent Variable",
"Density, Density Scale",
"Denying the antecedent",
"Denying the consequent",
"Deviation",
"Discrete Variable",
"Disjoint or Mutually Exclusive Events",
"Disjoint or Mutually Exclusive Sets",
"Distribution",
"Distribution Function, Empirical",
"Double-Blind, Double-Blind Experiment",
"Ecological Correlation",
"Element of a Set",
"Empirical Law of Averages",
"Empty Set",
"Endpoint Convention",
"Estimator",
"Event",
"Exhaustive",
"Expectation, Expected Value",
"Experiment",
"Explanatory Variable",
"Extrapolation",
"Factorial",
"Fair Bet",
"False Discovery Rate",
"Finite Population Correction",
"Fisher's exact test (for the equality of two percentages)",
"Football-Shaped Scatterplot",
"Frame, sampling frame",
"Frequency theory of probability",
"Frequency table",
"Fundamental Rule of Counting",
"Game Theory",
"Geometric Distribution",
"Geometric Mean",
"Heteroscedasticity",
"Histogram",
"Historical Controls",
"Homoscedasticity",
"House Edge",
"Hypergeometric Distribution",
"Hypothesis testing",
"iff, if and only if",
"Independent, independence",
"Independent and identically distributed (iid)",
"Independent Variable",
"Indicator Random Variable",
"Inter-quartile Range (IQR)",
"Interpolation",
"Intersection",
"Invalid (logical) argument",
"Joint Probability Distribution",
"Law of Averages",
"Law of Large Numbers",
"Limit",
"Linear Operation",
"Linear association",
"Location, Measure of",
"Logical argument",
"Logically equivalent, logical equivalence",
"Longitudinal study",
"Lower Quartile (LQ)",
"Margin of error",
"Marginal probability distribution",
"Markov's Inequality",
"Maximum Likelihood Estimate (MLE)",
"Mean, Arithmetic mean",
"Mean Squared Error (MSE)",
"Median",
"Member of a set",
"Method of Comparison",
"Minimax Strategy",
"Mode",
"Moment",
"Monotone, monotonic function",
"Multimodal Distribution",
"Multinomial Distribution",
"Multiplication rule",
"Multiplicity in hypothesis tests",
"Multivariate Data",
"Mutually Exclusive",
"Nearly normal distribution",
"Negative Binomial Distribution",
"No causation without manipulation",
"Nonlinear Association",
"Nonresponse",
"Nonresponse bias",
"Nonresponse rate",
"Normal approximation",
"Normal curve",
"Normal distribution",
"NOT, !, Negation, Logical Negation",
"Null hypothesis",
"Observational Study",
"Odds",
"One-sided Test",
"Ordinal Variable",
"Outcome Space",
"Outlier",
"P-value",
"Parameter",
"Partition",
"Payoff Matrix",
"Percentile",
"Permutation",
"Placebo",
"Placebo effect",
"Point of Averages",
"Poisson Distribution",
"Population",
"Population Mean",
"Population Percentage",
"Population Standard Deviation",
"Post hoc ergo propter hoc",
"Power",
"Premise, logical premise",
"Prima facie",
"Principle of insufficient reason (Laplace)",
"Probability",
"Probability density function",
"Probability Distribution",
"Probability Histogram",
"Probability Sample",
"Probability, Theories of",
"Proposition, logical proposition",
"Prosecutor's Fallacy",
"Qualitative Variable",
"Quantile",
"Quantitative Variable",
"Quartiles",
"Quota Sample",
"Random Error",
"Random Event",
"Random Experiment",
"Random Sample",
"Random Variable",
"Randomized Controlled Experiment",
"Range",
"Real number",
"Regression, Linear Regression",
"Regression Fallacy",
"Regression Toward the Mean, Regression Effect",
"Rejection region",
"Residual",
"Residual Plot",
"Resistant",
"Root-mean-square (RMS)",
"Root-mean-square error (RMSE)",
"rms Error of Regression",
"Sample",
"Sample Mean",
"Sample Percentage",
"Sample Size",
"Sound argument",
"Sample Standard Deviation, S",
"Sample Sum",
"Sample Survey",
"Sample Variance",
"Sampling distribution",
"Sampling error",
"Sampling unit",
"Scatterplot",
"Scientific Method",
"SD line",
"Secular Trend",
"Selection Bias",
"Self-Selection",
"Set",
"Significance, Significance level, Statistical significance",
"Simple Random Sample",
"Simpson's Paradox",
"Skewed Distribution",
"Spread, Measure of",
"Square-Root Law",
"Standard Deviation (SD)",
"Standard Error (SE)",
"Standard Normal Curve",
"Standard Units",
"Standardize",
"Statistic",
"Stratified Sample",
"Stratum",
"Studentized score",
"Student's t curve",
"Subject, Experimental Subject",
"Subset",
"Survey",
"Symmetric Distribution",
"Systematic error",
"Systematic sample",
"Systematic random sample",
"t test",
"Test Statistic",
"Transformation",
"Treatment",
"Treatment Effect",
"Treatment group",
"Two-sided Hypothesis test",
"Type I and Type II errors",
"Unbiased",
"Uncontrolled Experiment",
"Uncorrelated",
"Uncountable",
"Unimodal",
"Union",
"Unit",
"Univariate",
"Upper Quartile (UQ)",
"Valid (logical) argument",
"Variable",
"Variance, population variance",
"Venn Diagram",
"XOR, exclusive disjunction",
"z-score",
"Z statistic",
"z-test"
)
